# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "3. prod/terraform.tfstate"
    resource_group_name  = "resonanz-rg"
    storage_account_name = "tfstated252922f"
  }
}
